[build]
  functions = "functions-build"  # مسار دوال الوظائف المنشورة بعد البناء

[dev]
  publish = "dist"  # مسار مجلد النشر المحلي لموقعك

[functions]
  directory = "functions"  # مسار دوال الوظائف المصدر
  node_bundler = "esbuild"  # استخدام esbuild لتجميع دوال الوظائف

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
